### ISSUE TITLE
Season 3

### ISSUE THREAD

**Issue by ImDaRealAni** [novaprime/boris-legacy#1]
when is season 3 coming out

**Comment by unickorn** [comment]
could you provide steps to reproduce?

**Comment by provsalt** [comment]
Hi Ani, where did you go??

**Comment by mmm545** [comment]
Ani are you going to come back

**Comment by provsalt** [comment]
Season 3 once you come back :)

**Comment by unickorn** [comment]
Season 3 was released on January 16th.

**Comment by ImDaRealAni** [comment]
MY BIRTHDAY!!!

**Comment by provsalt** [comment]
> MY BIRTHDAY!!!

OMG HAI ANIIIIIIIIIIIIIIIII

**Comment by unickorn** [comment]
happy birthday ani

**Comment by mmm545** [comment]
happy birthday ani!!

**Comment by ImDaRealAni** [comment]
My birthday was on the release of Season III.

**Comment by mmm545** [comment]
poggers

**Comment by ImDaRealAni** [comment]
What season are you on now?

**Comment by unickorn** [comment]
3 still, though we're doing updates within the season.
